version: 2.1
orbs:
  node: circleci/node@4.1.0

defaults: &defaults
  working_directory: ~/repo
  executor:
   name: node/default
   tag: '10.23'

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages

      - run: npm run lerna -- bootstrap
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - run: npm run test-package

  release:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages

      - run: npm run lerna -- bootstrap
      - run: npm run build
      - deploy:
          command: npm run release

workflows:
  version: 2
  build-release:
    jobs:
      - release:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
